export default  [
  {
    Id: "1001",
    name: "Musa",
    img: "../../../images/musa.png",
    pollinator_friendly: true,
    edible: false,
    rain_garden: false,
    pet_kids_friendly: false,
    air_puryfying: true,
    sun_seeker: true,
    native: true,
    norwegian_nursery: true,
    size: 15,
    type: "grass",
    featured: true,
  },
  {
    Id: "1002",
    name: "Pertusem",
    img: "../../../images/pertusem.png",   
    pollinator_friendly: true,
    edible: true,
    rain_garden: false,
    pet_kids_friendly: false,
    air_puryfying: false,
    sun_seeker: false,
    native: false,
    norwegian_nursery: true,
    size: 75,
    type: "berry",
    featured: true,
  },
  {
    Id: "1003",
    name: "Philodendron",
    img: "../../../images/philodendron.png",
    pollinator_friendly: true,
    edible: true,
    rain_garden: false,
    pet_kids_friendly: true,
    air_puryfying: true,
    sun_seeker: false,
    native: true,
    norwegian_nursery: true,
    size: 25,
    type: "bush",
    featured: true,
  },
  {
    Id: "1004",
    name: "Musa",
    img: "../../../images/musa.png",
    pollinator_friendly: true,
    edible: false,
    rain_garden: false,
    pet_kids_friendly: false,
    air_puryfying: false,
    sun_seeker: false,
    native: false,
    norwegian_nursery: false,
    size: 55,
    type: "berry",
    featured: false,
  },
  {
    Id: "1005",
    name: "Pertusem",
    img: "../../../images/pertusem.png",
    pollinator_friendly: true,
    edible: true,
    rain_garden: true,
    pet_kids_friendly: true,
    air_puryfying: true,
    sun_seeker: true,
    native: true,
    norwegian_nursery: true,
    size: 45,
    type: "bush",
    featured: true,
  },
  {
    Id: "1006",
    name: "Philodendron",
    img: "../../../images/philodendron.png",
    pollinator_friendly: true,
    edible: true,
    rain_garden: false,
    pet_kids_friendly: false,
    air_puryfying: false,
    sun_seeker: false,
    native: true,
    norwegian_nursery: false,
    size: 45,
    type: "berry",
    featured: true,
  },
];
